# coding: utf-8

"""
    Cost Management

    The API for Cost Management.  You can find out more about     Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.sources_api import SourcesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSourcesApi(unittest.TestCase):
    """SourcesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.sources_api.SourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_source(self):
        """Test case for get_source

        Get a source  # noqa: E501
        """
        pass

    def test_get_source_stats(self):
        """Test case for get_source_stats

        Get a source statistics  # noqa: E501
        """
        pass

    def test_list_sources(self):
        """Test case for list_sources

        List the sources  # noqa: E501
        """
        pass

    def test_update_source(self):
        """Test case for update_source

        Update a source  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
