# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.dependency_error import DependencyError  # noqa: E501
from openapi_client.rest import ApiException

class TestDependencyError(unittest.TestCase):
    """DependencyError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DependencyError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.dependency_error.DependencyError()  # noqa: E501
        if include_optional :
            return DependencyError(
                errors = [
                    {"detail":"{'sources': ['RabbitMQ unavailable. Unable to update Source ID 1.']}","source":"detail","status":424}
                    ]
            )
        else :
            return DependencyError(
                errors = [
                    {"detail":"{'sources': ['RabbitMQ unavailable. Unable to update Source ID 1.']}","source":"detail","status":424}
                    ],
        )

    def testDependencyError(self):
        """Test DependencyError"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
