# coding: utf-8

"""
    Cost Management

    The API for Cost Management.  You can find out more about     Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.report_cost_all_of import ReportCostAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestReportCostAllOf(unittest.TestCase):
    """ReportCostAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportCostAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.report_cost_all_of.ReportCostAllOf()  # noqa: E501
        if include_optional :
            return ReportCostAllOf(
                data = [
                    [[{"date":"2018-05-28","total":{"infrastructure_cost":{"value":2564.775150581,"units":"USD"},"derived_cost":{"value":0,"units":"USD"},"cost":{"value":2564.775150581,"units":"USD"}},"delta":{"value":379.4398,"percent":-27.285392},"accounts":[{"account":"8577742690384","values":[{"date":"2018-05-28","account":"8577742690384","account_alias":"sample-account","infrastructure_cost":{"value":1498.92962634,"units":"USD"},"derived_cost":{"value":1,"units":"USD"},"cost":{"value":1499.92962634,"units":"USD"},"monthly_cost":{"value":0,"units":"USD"}}]},{"account":"9420673783214","values":[{"date":"2018-05-28","account":"9420673783214","account_alias":"9420673783214","infrastructure_cost":{"value":33,"units":"USD"},"derived_cost":{"value":22,"units":"USD"},"cost":{"value":55,"units":"USD"}}]}]}]]
                    ]
            )
        else :
            return ReportCostAllOf(
                data = [
                    [[{"date":"2018-05-28","total":{"infrastructure_cost":{"value":2564.775150581,"units":"USD"},"derived_cost":{"value":0,"units":"USD"},"cost":{"value":2564.775150581,"units":"USD"}},"delta":{"value":379.4398,"percent":-27.285392},"accounts":[{"account":"8577742690384","values":[{"date":"2018-05-28","account":"8577742690384","account_alias":"sample-account","infrastructure_cost":{"value":1498.92962634,"units":"USD"},"derived_cost":{"value":1,"units":"USD"},"cost":{"value":1499.92962634,"units":"USD"},"monthly_cost":{"value":0,"units":"USD"}}]},{"account":"9420673783214","values":[{"date":"2018-05-28","account":"9420673783214","account_alias":"9420673783214","infrastructure_cost":{"value":33,"units":"USD"},"derived_cost":{"value":22,"units":"USD"},"cost":{"value":55,"units":"USD"}}]}]}]]
                    ],
        )

    def testReportCostAllOf(self):
        """Test ReportCostAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
