# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tags_api import TagsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aws_tag_data(self):
        """Test case for get_aws_tag_data

        Query to obtain AWS tags  # noqa: E501
        """
        pass

    def test_get_azure_tag_data(self):
        """Test case for get_azure_tag_data

        Query to obtain AWS tags  # noqa: E501
        """
        pass

    def test_get_open_shift_aws_tag_data(self):
        """Test case for get_open_shift_aws_tag_data

        Query to obtain OpenShift-on-AWS tags  # noqa: E501
        """
        pass

    def test_get_open_shift_azure_tag_data(self):
        """Test case for get_open_shift_azure_tag_data

        Query to obtain OpenShift-on-Azure tags  # noqa: E501
        """
        pass

    def test_get_open_shift_tag_data(self):
        """Test case for get_open_shift_tag_data

        Query to obtain OpenShift tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
