# coding: utf-8

"""
    Cost Management

    The API for Cost Management.  You can find out more about     Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.report_open_shift_volume_all_of import ReportOpenShiftVolumeAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestReportOpenShiftVolumeAllOf(unittest.TestCase):
    """ReportOpenShiftVolumeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportOpenShiftVolumeAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.report_open_shift_volume_all_of.ReportOpenShiftVolumeAllOf()  # noqa: E501
        if include_optional :
            return ReportOpenShiftVolumeAllOf(
                data = [
                    [{"date":"2019-02","values":[{"date":"2019-02","usage":{"value":283.455815,"units":"GB-Mo"},"request":{"value":14058.333334,"units":"GB-Mo"},"capacity":{"value":13732.252982,"units":"GB-Mo"},"infrastructure_cost":{"value":4,"units":"USD"},"derived_cost":{"value":20.75,"units":"USD"},"cost":{"value":24.75,"units":"USD"}}]}]
                    ]
            )
        else :
            return ReportOpenShiftVolumeAllOf(
                data = [
                    [{"date":"2019-02","values":[{"date":"2019-02","usage":{"value":283.455815,"units":"GB-Mo"},"request":{"value":14058.333334,"units":"GB-Mo"},"capacity":{"value":13732.252982,"units":"GB-Mo"},"infrastructure_cost":{"value":4,"units":"USD"},"derived_cost":{"value":20.75,"units":"USD"},"cost":{"value":24.75,"units":"USD"}}]}]
                    ],
        )

    def testReportOpenShiftVolumeAllOf(self):
        """Test ReportOpenShiftVolumeAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
