# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.source_out_all_of_cost_models import SourceOutAllOfCostModels  # noqa: E501
from openapi_client.rest import ApiException

class TestSourceOutAllOfCostModels(unittest.TestCase):
    """SourceOutAllOfCostModels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SourceOutAllOfCostModels
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.source_out_all_of_cost_models.SourceOutAllOfCostModels()  # noqa: E501
        if include_optional :
            return SourceOutAllOfCostModels(
                uuid = 'd823a725-dc10-496a-af08-12533e4f8fe4', 
                name = 'My Great Cost Model'
            )
        else :
            return SourceOutAllOfCostModels(
        )

    def testSourceOutAllOfCostModels(self):
        """Test SourceOutAllOfCostModels"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
