# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.report_open_shift_memory_all_of import ReportOpenShiftMemoryAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestReportOpenShiftMemoryAllOf(unittest.TestCase):
    """ReportOpenShiftMemoryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportOpenShiftMemoryAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.report_open_shift_memory_all_of.ReportOpenShiftMemoryAllOf()  # noqa: E501
        if include_optional :
            return ReportOpenShiftMemoryAllOf(
                data = [
                    [[{"date":"2018-10","values":[{"date":"2018-10","usage":{"value":4.62038,"units":"GB-Hours"},"request":{"value":6.158921,"units":"GB-Hours"},"limit":{"value":405.835939,"units":"GB-Hours"},"capacity":{"value":17893.948761,"units":"GB-Hours"},"infrastructure_cost":{"value":4,"units":"USD"},"derived_cost":{"value":20.75,"units":"USD"},"cost":{"value":24.75,"units":"USD"}}]}]]
                    ]
            )
        else :
            return ReportOpenShiftMemoryAllOf(
                data = [
                    [[{"date":"2018-10","values":[{"date":"2018-10","usage":{"value":4.62038,"units":"GB-Hours"},"request":{"value":6.158921,"units":"GB-Hours"},"limit":{"value":405.835939,"units":"GB-Hours"},"capacity":{"value":17893.948761,"units":"GB-Hours"},"infrastructure_cost":{"value":4,"units":"USD"},"derived_cost":{"value":20.75,"units":"USD"},"cost":{"value":24.75,"units":"USD"}}]}]]
                    ],
        )

    def testReportOpenShiftMemoryAllOf(self):
        """Test ReportOpenShiftMemoryAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
