# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.user_out_all_of import UserOutAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestUserOutAllOf(unittest.TestCase):
    """UserOutAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserOutAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.user_out_all_of.UserOutAllOf()  # noqa: E501
        if include_optional :
            return UserOutAllOf(
                uuid = '57e60f90-8c0c-4bd1-87a0-2143759aae1c'
            )
        else :
            return UserOutAllOf(
                uuid = '57e60f90-8c0c-4bd1-87a0-2143759aae1c',
        )

    def testUserOutAllOf(self):
        """Test UserOutAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
