# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.settings_api import SettingsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.settings_api.SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_settings(self):
        """Test case for assign_settings

        Assign to cost management settings  # noqa: E501
        """
        pass

    def test_get_settings(self):
        """Test case for get_settings

        Query to cost management settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
