# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.report_instance_inventory import ReportInstanceInventory  # noqa: E501
from openapi_client.rest import ApiException

class TestReportInstanceInventory(unittest.TestCase):
    """ReportInstanceInventory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportInstanceInventory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.report_instance_inventory.ReportInstanceInventory()  # noqa: E501
        if include_optional :
            return ReportInstanceInventory(
                data = [
                    [[{"date":"2018-05-28","instance_types":[{"instance_type":"t2.medium","values":[{"date":"2018-05-28","instance_type":"t2.medium","usage":{"value":5,"units":"Hrs"},"infrastructure_cost":{"value":14.34,"units":"USD"},"derived_cost":{"value":4,"units":"USD"},"cost":{"value":18.34,"units":"USD"}}]},{"instance_type":"m5.2xlarge","values":[{"date":"2018-05-28","instance_type":"m5.2xlarge","usage":{"value":29,"units":"Hrs"},"infrastructure_cost":{"value":27.73,"units":"USD"},"derived_cost":{"value":8,"units":"USD"},"cost":{"value":35.73,"units":"USD"}}]}]}]]
                    ]
            )
        else :
            return ReportInstanceInventory(
                data = [
                    [[{"date":"2018-05-28","instance_types":[{"instance_type":"t2.medium","values":[{"date":"2018-05-28","instance_type":"t2.medium","usage":{"value":5,"units":"Hrs"},"infrastructure_cost":{"value":14.34,"units":"USD"},"derived_cost":{"value":4,"units":"USD"},"cost":{"value":18.34,"units":"USD"}}]},{"instance_type":"m5.2xlarge","values":[{"date":"2018-05-28","instance_type":"m5.2xlarge","usage":{"value":29,"units":"Hrs"},"infrastructure_cost":{"value":27.73,"units":"USD"},"derived_cost":{"value":8,"units":"USD"},"cost":{"value":35.73,"units":"USD"}}]}]}]]
                    ],
        )

    def testReportInstanceInventory(self):
        """Test ReportInstanceInventory"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
