# coding: utf-8

"""
    Cost Management

    The API for Cost Management.  You can find out more about     Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.report_costs_all_of import ReportCostsAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestReportCostsAllOf(unittest.TestCase):
    """ReportCostsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportCostsAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.report_costs_all_of.ReportCostsAllOf()  # noqa: E501
        if include_optional :
            return ReportCostsAllOf(
                data = [
                    [{"date":"2018-11","projects":[{"project":"monitoring","values":[{"date":"2018-11","project":"monitoring","infrastructure_cost":{"value":0.2,"units":"USD"},"derived_cost":{"value":3,"units":"USD"},"cost":{"value":3.2,"units":"USD"}}]},{"project":"metering","values":[{"date":"2018-11","project":"metering","infrastructure_cost":{"value":10.2,"units":"USD"},"derived_cost":{"value":30.3,"units":"USD"},"cost":{"value":40.5,"units":"USD"}}]}]}]
                    ]
            )
        else :
            return ReportCostsAllOf(
                data = [
                    [{"date":"2018-11","projects":[{"project":"monitoring","values":[{"date":"2018-11","project":"monitoring","infrastructure_cost":{"value":0.2,"units":"USD"},"derived_cost":{"value":3,"units":"USD"},"cost":{"value":3.2,"units":"USD"}}]},{"project":"metering","values":[{"date":"2018-11","project":"metering","infrastructure_cost":{"value":10.2,"units":"USD"},"derived_cost":{"value":30.3,"units":"USD"},"cost":{"value":40.5,"units":"USD"}}]}]}]
                    ],
        )

    def testReportCostsAllOf(self):
        """Test ReportCostsAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
