# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ProviderAuthenticationIn(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'provider_resource_name': 'str',
        'credentials': 'object'
    }

    attribute_map = {
        'provider_resource_name': 'provider_resource_name',
        'credentials': 'credentials'
    }

    def __init__(self, provider_resource_name=None, credentials=None, local_vars_configuration=None):  # noqa: E501
        """ProviderAuthenticationIn - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._provider_resource_name = None
        self._credentials = None
        self.discriminator = None

        if provider_resource_name is not None:
            self.provider_resource_name = provider_resource_name
        if credentials is not None:
            self.credentials = credentials

    @property
    def provider_resource_name(self):
        """Gets the provider_resource_name of this ProviderAuthenticationIn.  # noqa: E501


        :return: The provider_resource_name of this ProviderAuthenticationIn.  # noqa: E501
        :rtype: str
        """
        return self._provider_resource_name

    @provider_resource_name.setter
    def provider_resource_name(self, provider_resource_name):
        """Sets the provider_resource_name of this ProviderAuthenticationIn.


        :param provider_resource_name: The provider_resource_name of this ProviderAuthenticationIn.  # noqa: E501
        :type: str
        """

        self._provider_resource_name = provider_resource_name

    @property
    def credentials(self):
        """Gets the credentials of this ProviderAuthenticationIn.  # noqa: E501


        :return: The credentials of this ProviderAuthenticationIn.  # noqa: E501
        :rtype: object
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this ProviderAuthenticationIn.


        :param credentials: The credentials of this ProviderAuthenticationIn.  # noqa: E501
        :type: object
        """

        self._credentials = credentials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProviderAuthenticationIn):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProviderAuthenticationIn):
            return True

        return self.to_dict() != other.to_dict()
