# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ProviderBillingSourceOut(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bucket': 'str',
        'data_source': 'object',
        'uuid': 'str'
    }

    attribute_map = {
        'bucket': 'bucket',
        'data_source': 'data_source',
        'uuid': 'uuid'
    }

    def __init__(self, bucket=None, data_source=None, uuid=None, local_vars_configuration=None):  # noqa: E501
        """ProviderBillingSourceOut - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._bucket = None
        self._data_source = None
        self._uuid = None
        self.discriminator = None

        if bucket is not None:
            self.bucket = bucket
        if data_source is not None:
            self.data_source = data_source
        self.uuid = uuid

    @property
    def bucket(self):
        """Gets the bucket of this ProviderBillingSourceOut.  # noqa: E501


        :return: The bucket of this ProviderBillingSourceOut.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this ProviderBillingSourceOut.


        :param bucket: The bucket of this ProviderBillingSourceOut.  # noqa: E501
        :type: str
        """

        self._bucket = bucket

    @property
    def data_source(self):
        """Gets the data_source of this ProviderBillingSourceOut.  # noqa: E501


        :return: The data_source of this ProviderBillingSourceOut.  # noqa: E501
        :rtype: object
        """
        return self._data_source

    @data_source.setter
    def data_source(self, data_source):
        """Sets the data_source of this ProviderBillingSourceOut.


        :param data_source: The data_source of this ProviderBillingSourceOut.  # noqa: E501
        :type: object
        """

        self._data_source = data_source

    @property
    def uuid(self):
        """Gets the uuid of this ProviderBillingSourceOut.  # noqa: E501


        :return: The uuid of this ProviderBillingSourceOut.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ProviderBillingSourceOut.


        :param uuid: The uuid of this ProviderBillingSourceOut.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and uuid is None:  # noqa: E501
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProviderBillingSourceOut):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProviderBillingSourceOut):
            return True

        return self.to_dict() != other.to_dict()
