# coding: utf-8

"""
    Cost Management

    The API for Cost Management.  You can find out more about     Cost Management at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ReportOpenShiftGrouping(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cluster': 'list[str]',
        'project': 'list[str]',
        'node': 'list[str]',
        'tag': 'list[str]'
    }

    attribute_map = {
        'cluster': 'cluster',
        'project': 'project',
        'node': 'node',
        'tag': 'tag'
    }

    def __init__(self, cluster=None, project=None, node=None, tag=None, local_vars_configuration=None):  # noqa: E501
        """ReportOpenShiftGrouping - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cluster = None
        self._project = None
        self._node = None
        self._tag = None
        self.discriminator = None

        if cluster is not None:
            self.cluster = cluster
        if project is not None:
            self.project = project
        if node is not None:
            self.node = node
        if tag is not None:
            self.tag = tag

    @property
    def cluster(self):
        """Gets the cluster of this ReportOpenShiftGrouping.  # noqa: E501


        :return: The cluster of this ReportOpenShiftGrouping.  # noqa: E501
        :rtype: list[str]
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this ReportOpenShiftGrouping.


        :param cluster: The cluster of this ReportOpenShiftGrouping.  # noqa: E501
        :type: list[str]
        """

        self._cluster = cluster

    @property
    def project(self):
        """Gets the project of this ReportOpenShiftGrouping.  # noqa: E501


        :return: The project of this ReportOpenShiftGrouping.  # noqa: E501
        :rtype: list[str]
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ReportOpenShiftGrouping.


        :param project: The project of this ReportOpenShiftGrouping.  # noqa: E501
        :type: list[str]
        """

        self._project = project

    @property
    def node(self):
        """Gets the node of this ReportOpenShiftGrouping.  # noqa: E501


        :return: The node of this ReportOpenShiftGrouping.  # noqa: E501
        :rtype: list[str]
        """
        return self._node

    @node.setter
    def node(self, node):
        """Sets the node of this ReportOpenShiftGrouping.


        :param node: The node of this ReportOpenShiftGrouping.  # noqa: E501
        :type: list[str]
        """

        self._node = node

    @property
    def tag(self):
        """Gets the tag of this ReportOpenShiftGrouping.  # noqa: E501


        :return: The tag of this ReportOpenShiftGrouping.  # noqa: E501
        :rtype: list[str]
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ReportOpenShiftGrouping.


        :param tag: The tag of this ReportOpenShiftGrouping.  # noqa: E501
        :type: list[str]
        """

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportOpenShiftGrouping):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReportOpenShiftGrouping):
            return True

        return self.to_dict() != other.to_dict()
