# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ReportOpenShiftAzureOrdering(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cost': 'str',
        'usage': 'str',
        'delta': 'str',
        'subscription_guid': 'str',
        'resource_location': 'str',
        'service_name': 'str',
        'instance_type': 'str',
        'cluster': 'str',
        'project': 'str',
        'node': 'str'
    }

    attribute_map = {
        'cost': 'cost',
        'usage': 'usage',
        'delta': 'delta',
        'subscription_guid': 'subscription_guid',
        'resource_location': 'resource_location',
        'service_name': 'service_name',
        'instance_type': 'instance_type',
        'cluster': 'cluster',
        'project': 'project',
        'node': 'node'
    }

    def __init__(self, cost=None, usage=None, delta=None, subscription_guid=None, resource_location=None, service_name=None, instance_type=None, cluster=None, project=None, node=None, local_vars_configuration=None):  # noqa: E501
        """ReportOpenShiftAzureOrdering - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cost = None
        self._usage = None
        self._delta = None
        self._subscription_guid = None
        self._resource_location = None
        self._service_name = None
        self._instance_type = None
        self._cluster = None
        self._project = None
        self._node = None
        self.discriminator = None

        if cost is not None:
            self.cost = cost
        if usage is not None:
            self.usage = usage
        if delta is not None:
            self.delta = delta
        if subscription_guid is not None:
            self.subscription_guid = subscription_guid
        if resource_location is not None:
            self.resource_location = resource_location
        if service_name is not None:
            self.service_name = service_name
        if instance_type is not None:
            self.instance_type = instance_type
        if cluster is not None:
            self.cluster = cluster
        if project is not None:
            self.project = project
        if node is not None:
            self.node = node

    @property
    def cost(self):
        """Gets the cost of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The cost of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this ReportOpenShiftAzureOrdering.


        :param cost: The cost of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and cost not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `cost` ({0}), must be one of {1}"  # noqa: E501
                .format(cost, allowed_values)
            )

        self._cost = cost

    @property
    def usage(self):
        """Gets the usage of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The usage of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this ReportOpenShiftAzureOrdering.


        :param usage: The usage of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and usage not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `usage` ({0}), must be one of {1}"  # noqa: E501
                .format(usage, allowed_values)
            )

        self._usage = usage

    @property
    def delta(self):
        """Gets the delta of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The delta of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._delta

    @delta.setter
    def delta(self, delta):
        """Sets the delta of this ReportOpenShiftAzureOrdering.


        :param delta: The delta of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and delta not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `delta` ({0}), must be one of {1}"  # noqa: E501
                .format(delta, allowed_values)
            )

        self._delta = delta

    @property
    def subscription_guid(self):
        """Gets the subscription_guid of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The subscription_guid of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._subscription_guid

    @subscription_guid.setter
    def subscription_guid(self, subscription_guid):
        """Sets the subscription_guid of this ReportOpenShiftAzureOrdering.


        :param subscription_guid: The subscription_guid of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and subscription_guid not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `subscription_guid` ({0}), must be one of {1}"  # noqa: E501
                .format(subscription_guid, allowed_values)
            )

        self._subscription_guid = subscription_guid

    @property
    def resource_location(self):
        """Gets the resource_location of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The resource_location of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._resource_location

    @resource_location.setter
    def resource_location(self, resource_location):
        """Sets the resource_location of this ReportOpenShiftAzureOrdering.


        :param resource_location: The resource_location of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and resource_location not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `resource_location` ({0}), must be one of {1}"  # noqa: E501
                .format(resource_location, allowed_values)
            )

        self._resource_location = resource_location

    @property
    def service_name(self):
        """Gets the service_name of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The service_name of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this ReportOpenShiftAzureOrdering.


        :param service_name: The service_name of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and service_name not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `service_name` ({0}), must be one of {1}"  # noqa: E501
                .format(service_name, allowed_values)
            )

        self._service_name = service_name

    @property
    def instance_type(self):
        """Gets the instance_type of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The instance_type of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._instance_type

    @instance_type.setter
    def instance_type(self, instance_type):
        """Sets the instance_type of this ReportOpenShiftAzureOrdering.


        :param instance_type: The instance_type of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and instance_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `instance_type` ({0}), must be one of {1}"  # noqa: E501
                .format(instance_type, allowed_values)
            )

        self._instance_type = instance_type

    @property
    def cluster(self):
        """Gets the cluster of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The cluster of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this ReportOpenShiftAzureOrdering.


        :param cluster: The cluster of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and cluster not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `cluster` ({0}), must be one of {1}"  # noqa: E501
                .format(cluster, allowed_values)
            )

        self._cluster = cluster

    @property
    def project(self):
        """Gets the project of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The project of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ReportOpenShiftAzureOrdering.


        :param project: The project of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and project not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `project` ({0}), must be one of {1}"  # noqa: E501
                .format(project, allowed_values)
            )

        self._project = project

    @property
    def node(self):
        """Gets the node of this ReportOpenShiftAzureOrdering.  # noqa: E501


        :return: The node of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :rtype: str
        """
        return self._node

    @node.setter
    def node(self, node):
        """Sets the node of this ReportOpenShiftAzureOrdering.


        :param node: The node of this ReportOpenShiftAzureOrdering.  # noqa: E501
        :type: str
        """
        allowed_values = ["asc", "desc"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and node not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `node` ({0}), must be one of {1}"  # noqa: E501
                .format(node, allowed_values)
            )

        self._node = node

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportOpenShiftAzureOrdering):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReportOpenShiftAzureOrdering):
            return True

        return self.to_dict() != other.to_dict()
