# coding: utf-8

"""
    Cost Management

    The API for Project Koku and OpenShift cost management. You can find out more about Project Koku at [https://github.com/project-koku/](https://github.com/project-koku/).  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class SettingOut(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'fields': 'list[object]',
        'name': 'str',
        'component': 'str'
    }

    attribute_map = {
        'fields': 'fields',
        'name': 'name',
        'component': 'component'
    }

    def __init__(self, fields=None, name=None, component=None, local_vars_configuration=None):  # noqa: E501
        """SettingOut - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._fields = None
        self._name = None
        self._component = None
        self.discriminator = None

        if fields is not None:
            self.fields = fields
        if name is not None:
            self.name = name
        if component is not None:
            self.component = component

    @property
    def fields(self):
        """Gets the fields of this SettingOut.  # noqa: E501


        :return: The fields of this SettingOut.  # noqa: E501
        :rtype: list[object]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this SettingOut.


        :param fields: The fields of this SettingOut.  # noqa: E501
        :type: list[object]
        """

        self._fields = fields

    @property
    def name(self):
        """Gets the name of this SettingOut.  # noqa: E501


        :return: The name of this SettingOut.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SettingOut.


        :param name: The name of this SettingOut.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def component(self):
        """Gets the component of this SettingOut.  # noqa: E501


        :return: The component of this SettingOut.  # noqa: E501
        :rtype: str
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this SettingOut.


        :param component: The component of this SettingOut.  # noqa: E501
        :type: str
        """

        self._component = component

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SettingOut):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SettingOut):
            return True

        return self.to_dict() != other.to_dict()
